export { Tensor, isGradEnabled, noGrad, tensorAt } from "./tensor/Tensor";
export type { Shape } from "./tensor/shape";
export { CPUStorage, assertCPUStorage, cpuStorageFrom } from "./tensor/storage";
export type { GPUStorage, TensorDevice, TensorStorage } from "./tensor/storage";
export { Gradlith, Runtime, getBackend, getRuntime, manualSeed, noGradAsync, setBackend } from "./runtime";
export type { BackendName } from "./runtime";
export { Module } from "./nn/Module";
export { Dense, ReLU, Sigmoid, Softmax, Tanh } from "./nn/layers";
export { Sequential } from "./nn/Sequential";
export type { FitMetrics, FitOptions, SerializedModel } from "./nn/Sequential";
export { mse, binaryCrossEntropy, binaryCrossEntropyWithLogits, crossEntropy, crossEntropyWithLogits, sparseCrossEntropy } from "./nn/losses";
export type { LossFunction } from "./nn/losses";
export { SGD, Momentum, RMSProp, Adam } from "./optim/optimizers";
export type { Optimizer } from "./optim/optimizers";
export { xorDataset, circlesDataset, moonsDataset, spiralDataset } from "./datasets";
export type { Dataset } from "./datasets";
export { CPUBackend } from "./backends/CPUBackend";
export { WebGPUBackend, addShaderWGSL, reluShaderWGSL, matmulShaderWGSL } from "./backends/WebGPUBackend";
export type { Backend, BinaryOperation, BinaryOpSpec, BroadcastSpec, MatMulSpec, UnaryOperation, UnaryOpSpec } from "./backends/Backend";
export { diagnoseGradients } from "./diagnostics";
